version: '2'
services:
  serve:
    build: .
    command: node node_modules/@angular/cli/bin/ng serve -H 0.0.0.0 -e test
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/
      - /usr/src/node_modules
    ports:
      - "4200:4200"